# migrations/script.py.mako
"""create services table

Revision ID: 5ffdbf859ff9
Revises: deaea1644571
Create Date: 2025-09-27 21:32:47.386848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffdbf859ff9'
down_revision = 'deaea1644571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###