# migrations/script.py.mako
"""Add services and service_assignments tables

Revision ID: 71298443e5d8
Revises: 17a004d1c132
Create Date: 2025-09-30 23:53:33.035595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71298443e5d8'
down_revision = '17a004d1c132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_start_month', sa.Date(), nullable=False),
    sa.Column('billing_start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('link_capacity', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_assignments_id'), 'service_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_assignments_id'), table_name='service_assignments')
    op.drop_table('service_assignments')
    # ### end Alembic commands ###