# migrations/script.py.mako
"""Add payment module

Revision ID: 84984ac0b0d8
Revises: 4fa3632b79c8
Create Date: 2025-10-27 07:01:07.345472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84984ac0b0d8'
down_revision = '4fa3632b79c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###