# migrations/script.py.mako
"""Add Invoice model

Revision ID: 88d995150030
Revises: bd7ed0f8a869
Create Date: 2025-10-19 06:29:15.141654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d995150030'
down_revision = 'bd7ed0f8a869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###