# migrations/script.py.mako
"""Add service_assignments relationship to User

Revision ID: 8ea0f44d1679
Revises: 71298443e5d8
Create Date: 2025-09-30 23:55:29.966299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea0f44d1679'
down_revision = '71298443e5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###