# migrations/script.py.mako
"""Add service_stop_date field

Revision ID: bd7ed0f8a869
Revises: 8ea0f44d1679
Create Date: 2025-10-01 20:05:29.864289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7ed0f8a869'
down_revision = '8ea0f44d1679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_assignments', sa.Column('service_stop_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_assignments', 'service_stop_date')
    # ### end Alembic commands ###